---
# tasks file for redis

- name: Install Redis Package
  package: 
    name=redis 
    state=latest
  tags:
    - redis

- name: Start Redis service
  systemd: 
    name=redis 
    state=started 
    enabled=yes
  tags:
    - redis

- name: Change bind from 127.0.0.1 to 0.0.0.0
  # command: sed -e 's/bind 127.0.0.1/bind 0.0.0.0/' -i /etc/redis.conf
  lineinfile: 
    dest=/etc/redis.conf
    regexp='^bind '
    line='bind 0.0.0.0'
    state=present
  tags:
    - redis
  notify:
    - restart redis

- name: Allow redis related ports in INPUT chain
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
  loop: "{{ redis_iptables_allow_ports }}"
  tags:
    - redis