---
# tasks file for roles/CentOS-7.yml


- name: Install nginx
  package: name="{{ item }}" state=present
  loop:
    - nginx
  tags:
    - nginx

- name: Start nginx service
  systemd:
    state: started
    name: nginx
    daemon_reload: yes
    enabled: yes
  tags:
    - nginx
    
# - name: insert firewalld rule for nginx
#   firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
#   ignore_errors: yes

# - name: Nginx move sites.conf files
#   template: src=sites.conf dest=/etc/nginx/conf.d/
#   tags:
#     - nginx
#   notify:
#     - restart nginx