---
# tasks file for roles/CentOS-7.yml


- name: Install nginx
  package: name="{{ item }}" state=present
  loop:
    - nginx
  tags:
    - nginx

- name: Start nginx service
  systemd:
    state: started
    name: nginx
    daemon_reload: yes
    enabled: yes
  tags:
    - nginx

- name: Adding nginx config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  when: inventory_hostname == "bridge-00"
  with_items:
    - { src: "openldap.conf.j2", dest: "/etc/nginx/conf.d/openldap.conf" }
  tags:
    - nginx
  notify:
    - restart nginx

- name: Allow nginx related ports in INPUT chain
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
  loop: "{{ nginx_iptables_allow_ports }}"
  tags:
    - nginx

# - name: Nginx move sites.conf files
#   template: src=sites.conf dest=/etc/nginx/conf.d/
#   tags:
#     - nginx
#   notify:
#     - restart nginx