---
# handlers file for roles/php7-remi
- include: ../../../handlers/main.yml



- name: restart php72-php-fpm
  systemd:
    name: php72-php-fpm
    state: restarted
    daemon_reload: yes
    enabled: yes
