---
# tasks file for roles/Mongodb

# - name: "Adding Mongodb repositories"
#   copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: root
#     group: root
#   with_items:
#     - { src: mongodb.repo, dest: /etc/yum.repos.d/mongodb.repo }
#   tags:
#     - mongodb

- name: "Uninstall mongodb-org"
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - "mongodb-org*"
  tags:
    - mongodb

- name: "Install/Update Mongodb to the latest stable version"
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - mongodb-server
  tags:
    - mongodb

- name: Start Mongodb service
  systemd:
    state: started
    name: mongod
    daemon_reload: yes
    enabled: yes
  tags:
    - mongodb


- name: Change /etc/mongod.conf for mongodb
  lineinfile:
    dest: "/etc/mongod.conf"
    regexp: '{{ item.source }}'
    line: '{{ item.dest }}'
    backrefs: yes
  with_items: "{{ mongod_config_lines }}"
  notify:
    - restart mongodb
  tags:
    - mongodb

- name: Change /etc/mongos.conf for mongodb
  lineinfile:
    dest: "/etc/mongos.conf"
    regexp: '{{ item.source }}'
    line: '{{ item.dest }}'
    backrefs: yes
  with_items: "{{ mongod_config_lines }}"
  notify:
    - restart mongodb
  tags:
    - mongodb

- name: Add or modify nofile soft limit for the mongo user
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items:
    - { domain: mongod, type: soft, item: nproc, value: "64000"}
    - { domain: mongod, type: hard, item: nproc, value: "64000"}
    - { domain: mongod, type: soft, item: nofile, value: "64000"}
    - { domain: mongod, type: hard, item: nofile, value: "64000"}
  tags:
    - mongodb