---
# tasks file for roles/rsyslog

- name: "Adding Rsyslog and rsyslog-stable repositories"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  tags:
    - rsyslog
    - common_group
  with_items:
    - { src: rsyslog.repo, dest: /etc/yum.repos.d/rsyslog.repo }

- name: "Install/Update Rsyslog to the latest stable version"
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rsyslog_common_packages }}"
  tags:
    - rsyslog
    - common_group
  notify:
    - restart rsyslog
    - restart systemd_journald

- name: "Start rsyslog service"
  systemd:
    name: rsyslog
    state: started
    enabled: yes
  tags:
    - rsyslog
    - common_group

- name: "Install/Update Rsyslog components for rsyslog master server"
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rsyslog_master_packages }}"
  when: inventory_hostname == rsyslog_master
  tags:
    - rsyslog
    - common_group
    # - debug
  notify:
    - restart rsyslog
    - restart systemd_journald

- name: "Install/Update Rsyslog components for rsyslog slave server"
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rsyslog_slave_packages }}"
  when: inventory_hostname != rsyslog_master
  tags:
    - rsyslog
    - common_group
  notify:
    - restart rsyslog
    - restart systemd_journald


- name: "Allow rsyslog related ports in INPUT chain"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
  loop: "{{ rsyslog_iptables_allow_ports }}"
  when: inventory_hostname == rsyslog_master
  tags:
    - rsyslog
    - common_group

# start to install rsyslog.conf file.
- name: Update Rsyslog Config file for master.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    group: "root"
    owner: "root"
  with_items: "{{ rsyslog_master_sub_conf }}"
  when: inventory_hostname == rsyslog_master
  tags:
    - rsyslog
    - common_group
    - debug
  notify:
    - restart rsyslog
    - restart systemd_journald

# start to install rsyslog.conf file.
- name: Update Rsyslog Config file for slaves.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    group: "root"
    owner: "root"
  with_items: "{{ rsyslog_slave_sub_conf }}"
  when: inventory_hostname != rsyslog_master
  tags:
    - rsyslog
    - common_group
    # - debug
  notify:
    - restart rsyslog
    - restart systemd_journald

- name: Copy logrotate config files for weblogs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    group: "root"
    owner: "root"
  with_items:
    - { src: "logrotate/weblogs.j2", dest: "/etc/logrotate.d/weblogs", mode: "0644" }
  tags:
    - rsyslog
    - copyshell
  when: inventory_hostname == rsyslog_master

# - name: Install or Update mariadb-server to latest stable version
#   package:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - rsyslog-mmnormalize
#     # - mariadb-server
#     # - mariadb
#   tags:
#     - rsyslog
#   when: inventory_hostname == rsyslog_master
#   notify:
#     - start mariadb service

# - name: Install or Update nginx to latest stable version for master server
#   package:
#     name: "{{ item }}"
#     state: latest
#   with_items:
#     - nginx
#   tags:
#     - rsyslog
#   when: inventory_hostname != rsyslog_master and rsyslog_testing == "True"
#   notify:
#     - start nginx service
#     - restart nginx service