image: h.eefocus.tech/devops/docker/ansible:latest

variables:
  CI_DEBUG_TRACE: "false"

services:
  - name: docker:stable-dind
    command: ["--insecure-registry=$CI_REGISTRY"]

stages:
  - prepare
  - install
  
before_script:
  # - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
  # - docker login -u ek -p ek "${CI_REGISTRY}"
  - mkdir -p ~/.ssh/eefocus/
  # - echo "$SSH_PRIVATE_KEY" > ~/.ssh/eefocus/id_rsa.ali.git
  # - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  # - mv .ansible.cfg.a ~/.ansible.cfg
  - echo "$SSH_ROOT_PRIVATE_KEY" | tee ~/.ssh/eefocus/id_rsa.client
  - mv -fv .ansible.cfg.d ~/.ansible.cfg
  - chmod 600  -Rf ~/.ssh
  - mv inventory ~/

syntax_check:
  # <<: *default_tags
  stage: prepare
  script:
    - for job in `ls *.yml`; do ansible-playbook $job --syntax-check; done
  only:
    - master
  # when: manual

build_env:
  stage: install
  script:
    - ansible-playbook build-env.yml -e addition="\"$CI_JOB_URL\""
  only:
    - master
  # when: manual

