image: h.eefocus.tech/devops/docker/ansible:latest

variables:
  CI_DEBUG_TRACE: "false"

services:
  - name: docker:stable-dind
    command: ["--insecure-registry=$CI_REGISTRY"]

stages:
  - prepare
  - install
  
before_script:
  # - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
  # - docker login -u ek -p ek "${CI_REGISTRY}"
  - mkdir -p ~/.ssh/eefocus/
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/eefocus/id_rsa.ali.git
  - chmod 600  -Rf ~/.ssh
  - mv .ansible.cfg.a /root/.ansible.cfg
  - mv inventory /root/
  # - cat ~/.ssh/id_rsa

syntax_check:
  # <<: *default_tags
  stage: prepare
  script:
    - for job in `ls *.yml`; do ansible-playbook $job --syntax-check; done
  # only:
  #   - master
  # when: manual

playbooks:
  stage: install
  script:
    - ansible-playbook nginx.yml
  
  