---
- name: "Playbook for {{ host }}, {{ roles }}"
  hosts: "{{ host }}"
  connection: local
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest
  roles: "{{ roles }}"
  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
