---
- name: "Playbook for localhost"
  hosts: "{{ host_name }}"
  connection: local
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest
  roles: "{{ roles_list }}"
  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
