---
- name: Playbook for bridge group
  hosts: 
    - bridge
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - ocserv
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest

- name: "Playbook for jenkins server, jenkins and openldap-auth"
  hosts: 
    - jenkins
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - jenkins
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
  
- name: Playbook for sys group
  hosts: 
    - sys
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - openldap
    - dnsmasq
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
  

- name: Playbook for nginx group
  hosts: 
    - nginx
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - nginx
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
