---
- name: Proxy machines are gonna prepare.
  hosts: 
    - "{{ host }}"
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - base
    - nginx
    - ocserv
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
