---

- name: "Playbook for sys role, named: sys"
  hosts: 
    - sys
  become_user: root
  become: yes
  handlers:
    - include: ./handlers/main.yml role_name=sys_service
  tasks:
    - name: Roles for dnsmasq and openldap service
      block:
        - include_role: 
            name: dnsmasq
        - include_role:
            name: openldap
      rescue:
        - include: handlers/exception.yml role_name=sys_service
  tags:
    - sys


- name: "Playbook for base role, named: common_service"
  hosts:
    - common_group
  become_user: root
  become: yes
  handlers:
    - include: ./handlers/main.yml role_name=common_service
  # pre_tasks:
  #   - include_role: 
  #     name: base
  tasks:
    - name: Roles for common services
      block:
        - include_role: 
            name: base
        - include_role:
            name: rsyslog
        # - include_role: 
        #     name: zabbix
        - include_role: 
            name: openldap_auth
      rescue:
        - include: handlers/exception.yml role_name=common_service
  tags:
    - common_group

# - fail:
#   msg: "I've gone and failed the play!"
  # post_tasks:

# - name: "Playbook for ocserv role, named: ocserv"
#   hosts: 
#     - ocserv
#   become_user: root
#   become: yes
#   handlers:
#     - include: ./handlers/main.yml role_name=ocserv_service
#   tasks:
#     - name: Roles for ocserv service
#       block:
#         - include_role:
#             name: ocserv
#       rescue:
#         - include: handlers/exception.yml role_name=ocserv_service
#   tags:
#     - bridge


# - name: "Playbook for jenkins role, named: jenkins"
#   hosts: 
#     - jenkins
#   become_user: root
#   become: yes
#   handlers:
#     - include: ./handlers/main.yml role_name=jenkins_service
#   tasks:
#     - name: Roles for jenkins service
#       block:
#         - include_role: 
#             name: jenkins
#       rescue:
#         - include: handlers/exception.yml role_name=jenkins_service
#   tags:
#     - jenkins


- name: "Playbook for nginx role, named: nginx"
  hosts: 
    - nginx
  become_user: root
  become: yes
  handlers:
    - include: ./handlers/main.yml role_name=nginx_service
  tasks:
    - name: Roles for nginx service
      block:
        - include_role: 
            name: nginx
      rescue:
        - include: handlers/exception.yml role_name=nginx_service
  tags:
    - nginx


- name: "Playbook for cache role, named: cache"
  hosts: 
    - cache
  become_user: root
  become: yes
  handlers:
    - include: ./handlers/main.yml role_name=cache_service
  tasks:
    - name: Roles for cache service
      block:
        - include_role:
            name: redis
        - include_role:
            name: memcache
        - include_role:
            name: memcacheX
        - include_role:
            name: mongodb
        # - include_role:
        #     name: rabbitmq
        - include_role:
            name: sphinx
      rescue:
        - include: handlers/exception.yml role_name=cache_service
  tags:
    - cache


- name: "Playbook for nodejs role, named: nodejs"
  hosts: 
    - nodejs
  become_user: root
  become: yes
  handlers:
    - include: ./handlers/main.yml role_name=nodejs_service
  tasks:
    - name: Roles for nodejs service
      block:
        - include_role:
            name: nodejs
      rescue:
        - include: handlers/exception.yml role_name=nodejs_service
  tags:
    - nodejs


- name: "Playbook for php5_remi role, named: php5_remi"
  hosts: 
    - php5_remi
  become_user: root
  become: yes
  handlers:
    - include: ./handlers/main.yml role_name=php5_remi_service
  tasks:
    - name: Roles for php5_remi service
      block:
        - include_role:
            name: php5_remi
      rescue:
        - include: handlers/exception.yml role_name=php5_remi_service
  tags:
    - php5_remi


- name: "Playbook for php7_remi role, named: php7_remi"
  hosts: 
    - php7_remi
  become_user: root
  become: yes
  handlers:
    - include: ./handlers/main.yml role_name=php7_remi_service
  tasks:
    - name: Roles for php7_remi service
      block:
        - include_role:
            name: php7_remi
      rescue:
        - include: handlers/exception.yml role_name=php7_remi_service
  tags:
    - php7_remi

