---

- name: "Playbook for base role, named: common_service"
  hosts: 
    - common_group
  become_user: root
  become: yes

  handlers:
    - include: ./handlers/main.yml role_name=common_service

  # pre_tasks:
  #   - include_role: 
  #     name: base
  tasks:
    - name: Roles for common services
      block:
        - include_role: 
            name: base
        - include_role: 
            name: rsyslog
        - include_role: 
            name: zabbix
      rescue:
        # - include_role:
        #   name: php5
        #   tasks_fram: failure
        - include: handlers/exception.yml role_name=common_service
        # - debug:
        #   msg: 'I caught an error, ansible_hostname: {{ ansible_hostname }}, inventory_hostname: {{ inventory_hostname }}, ansible_failed_task.name: {{ ansible_failed_task.name }}, ansible_failed_result: {{ ansible_failed_task }}'

    # - rescure:
    #   - debug:
    #     msg: 'hihi'
    # block:
    #   - include_role:
    #     name:
    #       - base
    #   - fail:
    #     msg: "I've gone and failed the play!"
#   roles:
#     - base

# - fail:
#   msg: "I've gone and failed the play!"
  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti
  




# - name: "Playbook for base role"
#   hosts: 
#     - all
#   become_user: root
#   become: yes

#   # pre_tasks:
#   #   - name: Pre Task => Update Yum
#   #     dnf: name=* state=latest

#   roles:
#     - base

#   # post_tasks:
#   #   - name: Successfully finished
#   #     mattermost:
#   #       url: http://218.4.226.238:8065
#   #       api_key: yosqbqtpkp818cax6kzh89ctyr
#   #       text: "hhhiiixxxx"
#   #       username: "testing.yml"
#   #       channel: "bashme"
#   #     tags:
#   #       - noti

# - name: "Playbook for ocserv group"
#   hosts: 
#     - ocserv
#   become_user: root
#   become: yes

#   # pre_tasks:
#   #   - name: Pre Task => Update Yum
#   #     dnf: name=* state=latest

#   roles:
#     - ocserv

#   # post_tasks:
#   #   - name: Successfully finished
#   #     mattermost:
#   #       url: http://218.4.226.238:8065
#   #       api_key: yosqbqtpkp818cax6kzh89ctyr
#   #       text: "hhhiiixxxx"
#   #       username: "testing.yml"
#   #       channel: "bashme"
#   #     tags:
#   #       - noti

# - name: "Playbook for dnsmasq group"
#   hosts: 
#     - dnsmasq
#   become_user: root
#   become: yes

#   # pre_tasks:
#   #   - name: Pre Task => Update Yum
#   #     dnf: name=* state=latest

#   roles:
#     - dnsmasq

#   # post_tasks:
#   #   - name: Successfully finished
#   #     mattermost:
#   #       url: http://218.4.226.238:8065
#   #       api_key: yosqbqtpkp818cax6kzh89ctyr
#   #       text: "hhhiiixxxx"
#   #       username: "testing.yml"
#   #       channel: "bashme"
#   #     tags:
#   #       - noti


# - name: "Playbook for jenkins group"
#   hosts: 
#     - jenkins
#   become_user: root
#   become: yes

#   # pre_tasks:
#   #   - name: Pre Task => Update Yum
#   #     dnf: name=* state=latest

#   roles:
#     - jenkins

#   # post_tasks:
#   #   - name: Successfully finished
#   #     mattermost:
#   #       url: http://218.4.226.238:8065
#   #       api_key: yosqbqtpkp818cax6kzh89ctyr
#   #       text: "hhhiiixxxx"
#   #       username: "testing.yml"
#   #       channel: "bashme"
#   #     tags:
#   #       - noti


# - name: "Playbook for nginx group"
#   hosts: 
#     - nginx
#   become_user: root
#   become: yes

#   # pre_tasks:
#   #   - name: Pre Task => Update Yum
#   #     dnf: name=* state=latest

#   roles:
#     - nginx

#   # post_tasks:
#   #   - name: Successfully finished
#   #     mattermost:
#   #       url: http://218.4.226.238:8065
#   #       api_key: yosqbqtpkp818cax6kzh89ctyr
#   #       text: "hhhiiixxxx"
#   #       username: "testing.yml"
#   #       channel: "bashme"
#   #     tags:
#   #       - noti



# - name: "Playbook for common group"
#   hosts: 
#     # the same as zabbix, openldap_auth
#     - rsyslog
#   become_user: root
#   become: yes

#   # pre_tasks:
#   #   - name: Pre Task => Update Yum
#   #     dnf: name=* state=latest

#   roles:
#     - openldap_auth
#     - zabbix
#     - rsyslog

#   # post_tasks:
#   #   - name: Successfully finished
#   #     mattermost:
#   #       url: http://218.4.226.238:8065
#   #       api_key: yosqbqtpkp818cax6kzh89ctyr
#   #       text: "hhhiiixxxx"
#   #       username: "testing.yml"
#   #       channel: "bashme"
#   #     tags:
#   #       - noti
