---


- name: "Playbook for ocserv group"
  hosts: 
    - ocserv
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - ocserv

  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti

- name: "Playbook for dnsmasq group"
  hosts: 
    - dnsmasq
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - dnsmasq

  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti


- name: "Playbook for sys group"
  hosts: 
    - sys
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - sys

  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti


- name: "Playbook for jenkins group"
  hosts: 
    - jenkins
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - jenkins

  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti


- name: "Playbook for nginx group"
  hosts: 
    - nginx
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - nginx

  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti



- name: "Playbook for common group"
  hosts: 
    - rsyslog
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - openldap_auth
    - zabbix
    - rsyslog

  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti
