---
- name: Playbook for role dnsmasq
  hosts: 
    - dnsmasq
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - dnsmasq

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
