---
- name: "Playbook for jenkins server, jenkins and openldap-auth"
  hosts: 
    - "jenkins"
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - jenkins
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
