---
- name: "Playbook for jenkins server, jenkins"
  hosts: 
    - "{{ host }}"
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - jenkins

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest

- name: "Playbook for jenkins server, openldap-auth"
  hosts: 
    - "{{ host }}"
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
