---
- name: Playbook for jenkins role
  hosts: 
    - jenkins
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - jenkins

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest

