---
- name: Playbook for nginx group
  hosts: 
    - nginx
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - nginx
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
