---
- name: Playbook for cirmall role
  hosts: 
    - nodejs
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - nodejs

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
