---
- name: Playbook for openldap-auth role
  hosts: 
    - openldap-auth
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest

