---
- name: Playbook for rsyslog role
  hosts: 
    - rsyslog
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - rsyslog

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
