---
- name: Playbook for sys servers
  hosts: 
    - "{{ host }}"
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - base
    - openldap
    # - ansible
    - dnsmasq
    - openldap-auth

  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
