---
- name: Proxy machines are gonna prepare.
  hosts: 
    # - localhost
    # - l201
    # - l196
    # - master
    - localtesting
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    # - base
    # - iptables
    # - nginx
    # - nodejs
    # - dnsmasq
    # - php5
    # - php7
    # - rsyslog
    # - redis
    # - memcache
    # - openldap
    # - rabbitmq
    # - mongodb
    # - php5-remi
    - php7-remi
    # - sphinx



  # post_tasks:
  #   - name: post tasks
  #     dnf: name=* state=latest
