---
- name: "Playbook testing for {{ host }}"
  hosts: 
    - rsyslog
  become_user: root
  become: yes
  handlers:
    - include: ./handlers/main.yml

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  roles:
    - { role: dnsmasq, role_name: dnsmasqxx, when: inventory_hostname == 'sys-00' }
    - { role: rsyslog, role_name: rsyslogxx, when: inventory_hostname == 'sys-00' }

  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti