---
- name: "Playbook testing for {{ host }}"
  hosts: 
    # - localhost
    # - l201
    # - l196
    # - all
    # - "{{ host }}"
    - "{{ host }}"
    # - libvirt
    # - localtesting
    # - virtualbox
  become_user: root
  become: yes

  # pre_tasks:
  #   - name: Pre Task => Update Yum
  #     dnf: name=* state=latest

  # roles:
  #   - base
    # - iptables
    # - nginx
    # - nodejs
    # - dnsmasq
    # - php5
    # - php7
    # - rsyslog
    # - redis
    # - memcache
    # - openldap
    # - rabbitmq
    # - mongodb
    # - php5-remi
    # - php7-remi
    # - sphinx
    # - openldap-auth

  # post_tasks:
  #   - name: Successfully finished
  #     mattermost:
  #       url: http://218.4.226.238:8065
  #       api_key: yosqbqtpkp818cax6kzh89ctyr
  #       text: "hhhiiixxxx"
  #       username: "testing.yml"
  #       channel: "bashme"
  #     tags:
  #       - noti

  post_tasks:
    - name: Successfully finished
      slack:
        token: "TD91LBXBM/BDAF3HP38/XIrbT3A1jVhRGJST1V3DcKtr"
        channel: "rsyslog"
        msg: "Failed in msg field @Xiaoshi <@UFMESDLQ4> <@>"
        attachments:
          - text: hi failed.
            color: "#FF0000"
      tags:
        - noti