---
# tasks file for memcached

- name: Install memcached Package
  package: 
    name=memcached 
    state=latest
  tags:
    - memcached

- name: Start memcached service
  systemd: 
    name=memcached 
    state=started 
    enabled=yes
  tags:
    - memcached

  # command: sed -e 's/bind 127.0.0.1/bind 0.0.0.0/' -i /etc/memcached.conf
- name: Change bind from 127.0.0.1 to 0.0.0.0
  lineinfile: 
    dest=/etc/sysconfig/memcached
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
    state=present
  with_items: "{{ memcahced_config }}"
  tags:
    - memcached
  notify:
    - restart memcached

- name: Allow memcached related ports in INPUT chain
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
  with_items: "{{ memcached_iptables_allow_ports }}"
  tags:
    - memcached
