---
# handlers file for roles/base

# - include: ../../../handlers/main.yml
# - include: ../../../handlers/main.yml

- name: restart network
  service: 
    name: network 
    state: restarted
    enabled: yes
