---
# handlers file for roles/jenkins
handlers:
- include: ../../../handlers/main.yml

- name: "restart jenkins"
  systemd:
    state: restarted
    name: jenkins
    daemon_reload: yes
    enabled: yes