---

# notification handlers
- name: Send Slack notification.
  slack:
    token: "TD91LBXBM/BFRTW9P54/SwzT2sC2UJPsSWj3NRKW1sl5"
    msg: "Service in role: {{ role_name }} @{{ inventory_hostname }} ({{ ansible_eth0['ipv4']['address'] }}) is restarted/changed!"
    username: "aliyun >>> {{ inventory_hostname }} ({{ ansible_eth0['ipv4']['address'] }})"
    channel: "#sync-nginx-conf"
  # when: inventory_hostname != "cache-1"
  run_once: true
  listen:
    - "crontab updated"
    - "restart jenkins"
    - "restart sssd"

- name: Send Mattermost notification.
  mattermost:
    url: "http://218.4.226.238:8065"
    api_key: "if11n7se63ycpx43sh37yskkyo"
    text: "Service in role: {{ role_name }}@{{ inventory_hostname }} ({{ ansible_eth0['ipv4']['address'] }}) is restarted/changed!"
    username: "aliyun >>> {{ inventory_hostname }} ({{ ansible_eth0['ipv4']['address'] }})"
  # when: inventory_hostname != "cache-1"
  run_once: true
  listen:
    - "crontab updated"
    - "restart jenkins"
    - "restart sssd"

# - name: " -> update dnsresolve in all group servers {{ groups['all'] }}"
#   lineinfile:
#     dest: "/etc/resolv.conf"
#     regexp: '^nameserver'
#     line: 'nameserver    {{ ldap_ip_address }}'
#     backrefs: "yes"
#   delegate_to: "{{ item }}"
#   loop: "{{ groups['all'] }}"
#   listen:
#     - "restart dnsmasq"