---
# tasks file for roles/php5
# - name: "Create {{ fpm_group }} for php5"
#   group:
#     name: "{{ fpm_group }}"
#     state: present
#   tags:
#     - php5_remi

# - name: "Create {{ fpm_user }} for php5"
#   user:
#     name: "{{ fpm_user }}"
#     comment: "php user"
#     create_home: no
#     state: present
#     group: "{{ fpm_group }}"
#   tags:
#     - php5_remi


- name: "Adding remi repositories"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  tags:
    - php5_remi
  with_items:
    - { src: php-remi.repo, dest: /etc/yum.repos.d/php-remi.repo }

- name: "Remove existing php packages."
  package: 
    name: "{{ item }}"
    state: absent
  loop:
    - php56-php-pecl-redis
    - php56-php-pecl-memcache
  tags:
    - php5_remi

- name: "Install/Update php56 to the latest stable version"
  package:
    name: "{{ item }}"
    state: present
  loop:
    # - php56-php-pecl-redis
    # - php56-php-pecl-memcache
    - php56-php-pecl-memcached
    - php56-php-pecl-apcu
    # fixing for moore8
    # - php56-php-pecl-sphinx
    - php56-php-pecl-mongo
    - php56-php-pecl-mongodb
    - php56-php-mbstring
    - php56-php-mysqlnd
    - php56-php-opcache
    - php56-php-gd
    - php56-php-fpm
    - php56-php-mcrypt
    - php56-php-intl
    - php56-php-bcmath
    - php56-php-soap
    - php56-php-xmlrpc
    - php56-php-cli
    - php56-php-devel
  tags:
    - php5_remi

- name: "Install php extensions"
  shell: >
    echo "" | {{ php56_root }}/bin/pecl install {{ item.extension }}
  args:
    creates: "{{ item.creates }}"
  with_items: "{{ php5_remi_extensions }}"
  tags:
    - php5_remi

- name: "Install extension config files."
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ php5_remi_extension_configs }}"
  tags:
    - php5_remi

- name: "Start php56-php-fpm service"
  systemd:
    name: php56-php-fpm
    state: started
    enabled: yes
  tags:
    - php5_remi

- name: Changes to the php.ini settings.
  lineinfile:
    dest: "/etc/opt/remi/php56/php.ini"
    regexp: '{{ item.source }}'
    line: '{{ item.dest }}'
    backrefs: yes
  with_items: "{{ php5_remi_ini_config_lines }}"
  tags:
    - php5_remi
  notify: restart php56-php-fpm

- name: Changes to the php-fpm.conf file.
  lineinfile:
    dest: "/etc/opt/remi/php56/php-fpm.d/www.conf"
    regexp: '{{ item.source }}'
    line: '{{ item.dest }}'
    backrefs: yes
  with_items: "{{ php5_remi_fpm_config_lines }}"
  ignore_errors: yes
  tags:
    - php5_remi
  notify: restart php56-php-fpm
