---
# handlers file for roles/php5_remi
# - include: ../../../handlers/main.yml

- name: restart php56-php-fpm
  systemd:
    name: php56-php-fpm
    state: restarted
    daemon_reload: yes
    enabled: yes