---
# handlers file for roles/sphinx
- include: ../../../handlers/main.yml

- name: restart sphinx_search
  systemd:
    name: sphinxsearch
    state: restarted
    daemon_reload: yes
    enabled: yes