---
# tasks file for roles/dnsmasq

- name: Install dnsmasq
  package:
    name: "{{ item }}"
    state: present
  loop:
    - dnsmasq
  tags:
    - dnsmasq

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags:
    - dnsmasq

- name: Replace lines in dns config file.
  lineinfile:
    dest: "/etc/dnsmasq.conf"
    regexp: '{{ item.source }}'
    line: '{{ item.dest }}'
    backrefs: "yes"
  with_items: "{{ dnsmasq_config_lines }}"
  tags:
    - dnsmasq
  notify: restart dnsmasq

- name: Copy config file that contains custom rules
  template: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
  tags:
    - dnsmasq
  with_items:
    - { src: sample.conf, dest: /etc/dnsmasq.d/sample.conf }
    - { src: resolv.dnsmasq.conf, dest: /etc/resolv.dnsmasq.conf }
  notify:
    - restart dnsmasq
    
- name: Allow dnsmasq related ports in INPUT chain
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    action: insert
    comment: "dnsmasq related tcp ports"
  loop: "{{ dnsmasq_iptables_allow_ports }}"
  tags:
    - dnsmasq

- name: Allow dnsmasq udp ports in INPUT chain 
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: "53"
    jump: ACCEPT
    action: insert
    comment: "dnsmasq related udp ports"
  tags:
    - dnsmasq
