---
# handlers file for roles/rsyslog
- include: ../../../handlers/main.yml



- name: restart rsyslog service
  service:
    name: rsyslog
    state: restarted
    enabled: yes

# - include: ../../../global/handlers.yml