---
# handlers file for roles/rsyslog
# - import_tasks: ../../../handlers/main.yml

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: restart systemd_journald
  service:
    name: systemd-journald.socket
    state: restarted
    enabled: yes
