---
# tasks file for roles/CentOS-7.yml

- name: Disable the selinux.
  selinux:
    state: disabled


- name: Adding SNAT for aliyun servers without public ip
  iptables:
    table: nat
    action: insert
    chain: POSTROUTING
    source: "192.168.88.0/24"
    to_source: "192.168.88.88"
    jump: SNAT
    comment: "snat settings"
  when: inventory_hostname == 'bridge-00'
  tags:
    - base
    - common_group
    - base-motd

- name: Install / Enable EPEL repo for servers.
  package: 
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
  tags:
    - base
    - common_group

# - name: Download and replace the CentOS-7.repo file.
#   get_url:
#     url: "{{ item.url }}"
#     dest: "{{ item.dest }}"
#     checksum: "sha256:{{ item.checksum }}"
#     timeout: 60
#   loop: "{{ centos_repos }}"
#   tags:
#     - base
    
# - name: Import the GPG keys for CentOS repositories.
#   rpm_key: 
#     state: present
#     key: "{{ item }}"
#   with_items:
#     - /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
#     - /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
#   tags:
#     - base

# - name: Update all packages on CentOS
#   package: name="*" state=latest
#   tags:
#     - base

- name: Install basic tools and packages.
  package: 
    name: "{{ item }}" 
    state: present
  loop:
    - lsof
    - telnet
    - vim
    - tree
    - libselinux-python
    - yum-utils
    - python2-pip
    - python3-pip
    - bind-utils
    - iptables-services
    - nfs-utils
    - pyOpenSSL
  tags:
    - base
    - common_group

- name: Install basic pip packages.
  pip:
    name: "{{ item }}"
    extra_args: -i "{{ centos_pip_mirror }}"
  loop:
    - docker-py
    - passlib
  tags:
    - base
    - common_group

- name: Change the motd file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "motd.j2", dest: "/etc/motd" }
  tags:
    - base
    - common_group
    - base-motd

- name: Settings to sysctl.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  loop: "{{ sysctl_file_settings }}"
  tags:
    - base
    - common_group
  
# - name: "update dnsresolve in all group servers"
#   lineinfile:
#     dest: "/etc/resolv.conf"
#     regexp: '^nameserver'
#     insertbefore: "^; generated.*"
#     line: 'nameserver    {{ ldap_ip_address }}'
#     backrefs: "yes"
#   when: inventory_hostname != 'master' and inventory_hostname != 'slave1' and inventory_hostname != 'slave2'
#   tags:
#     - base

- name: Adding custom dns server for ecs
  blockinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    block: |
      {{ item }}
    marker: "# {mark} ansible managed block {{ item }}"
  loop:
    - "DNS1=192.168.88.90"
    # - "DNS2=114.114.114.114"
    # - "DNS3=100.100.2.136"
  when: inventory_hostname != 'sys-00' and inventory_hostname != 'misc-usa-00'
  notify:
    - restart network

- name: Create /data directory for server
  file:
    path: "/data/"
    state: directory
  when: inventory_hostname != 'misc-usa-00' and inventory_hostname != 'monitor-00'
  tags:
    - base
    - common_group
    - base-motd
    
- name: Mount /data/ partition
  mount:
    src: 337b949743-yab25.cn-shanghai.nas.aliyuncs.com:/
    fstype: nfs
    path: /data/
    opts: vers=4,minorversion=0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev,noresvport
    state: mounted
    boot: yes
  when: inventory_hostname != 'misc-usa-00' and inventory_hostname != 'monitor-00'
  tags:
    - base
    - common_group
    - base-motd
    
- name: Change the hostname step
  hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - base
    - common_group
    - base-motd